### ISSUE TITLE
Incomplete initialization of the class StrawberryFieldsSimulator: missing _capabilities

### ISSUE THREAD

**Issue by MichelNowak1** [XanaduAI/pennylane-sf#27]
#### Issue description
The class StrawberryFieldsSimulator derives from Device (pennylane)

At the initializatinon of the qnode when the backend strawberryfields.fock is used, it returns an error. The traceback is given below.
self.device.capabilities() returns {} because it is not initialized properly.
A fix for it is to add 
```
_capabilities = {"model": "cv"}  
```
in the class StrawberryFieldsSimulator(Device) in pennylane-sf/simulator.py

* *Expected behavior:* 
Iter:     1 | Cost: 0.3447069 
Iter:     2 | Cost: 0.3161090 
Iter:     3 | Cost: 0.2925777 
Iter:     4 | Cost: 0.2721567
etc...

* *Actual behavior:*
Nothing

* *Reproduces how often:*
Always

#### System information

* **Operating system:**
Ubuntu Linux 18.04
* **PennyLane-SF version:**
0.6.0
* **Python version:**
3.6.8
* **NumPy and SciPy versions:**
  These can be found by running
Numpy: 1.17.4
Scipy: 1.3.1

* **Installation method:**

Pennylane-SF installed by github. Branch Master, last commit:
e4b67b0154b7af88b1beb3abd1da0701d131a385
Josh Izaac
Fri Oct 18 17:24:13 2019 -0400
dev version

#### Source code and tracebacks
```
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer

dev = qml.device("strawberryfields.fock", wires=1, cutoff_dim=10)

def layer(v):
    # Matrix multiplication of input layer
    qml.Rotation(v[0], wires=0)
    qml.Squeezing(v[1], 0.0, wires=0)
    qml.Rotation(v[2], wires=0)

    # Bias
    qml.Displacement(v[3], 0.0, wires=0)

    # Element-wise nonlinear transformation
    qml.Kerr(v[4], wires=0)


@qml.qnode(dev)
def quantum_neural_net(var, x=None):
    # Encode input x into quantum state
    qml.Displacement(x, 0.0, wires=0)

    # "layer" subcircuits
    for v in var:
        layer(v)

    return qml.expval(qml.X(0))

def square_loss(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2

    loss = loss / len(labels)
    return loss

def cost(var, features, labels):
    preds = [quantum_neural_net(var, x=x) for x in features]
    return square_loss(labels, preds)

X = np.linspace(-1, 1, 50)
Y = np.sin(np.pi*X)

np.random.seed(0)
num_layers = 4
var_init = 0.05 * np.random.randn(num_layers, 5)

opt = AdamOptimizer(0.01, beta1=0.9, beta2=0.999)

var = var_init
for it in range(500):
    var = opt.step(lambda v: cost(v, X, Y), var)
    print("Iter: {:5d} | Cost: {:0.7f} ".format(it + 1, cost(var, X, Y)))

x_pred = np.linspace(-1, 1, 50)
predictions = [quantum_neural_net(var, x=x_) for x_ in x_pred]
```

### Traceback (most recent call last):
  File "qnn_1d.py", line 21, in <module>
    def quantum_neural_net(var, x=None):
  File "/home/michel/codes/pennylane/pennylane/qnodes/decorator.py", line 194, in qfunc_decorator
    properties=properties,
  File "/home/michel/codes/pennylane/pennylane/qnodes/decorator.py", line 106, in QNode
    node = PARAMETER_SHIFT_QNODES[model](func, device, mutable=mutable, properties=properties)
  File "/home/michel/codes/pennylane/pennylane/qnodes/jacobian.py", line 32, in __init__
    super().__init__(func, device, mutable=mutable, properties=properties)
  File "/home/michel/codes/pennylane/pennylane/qnodes/base.py", line 197, in __init__
    self.model = self.device.capabilities()["model"]  #: str: circuit type, in {'cv', 'qubit'}
KeyError: 'model'

**Comment by josh146** [comment]
Thanks for catching this @MichelNowak1 - this change (requiring the `_capabilities` dictionary) is only in PL master, not the latest release yet, however it makes sense to also add this to master here. I'll work on a small PR now
